### ISSUE TITLE
Docker build failing...

### ISSUE THREAD

**Issue by swarupmohalik** [dlshriver/DNNF#2]
Docker build . -t dlshriver/dnnf failing ..
:
Collecting torch~=1.6
  Downloading torch-1.9.0-cp37-cp37m-manylinux1_x86_64.whl (831.4 MB)
Traceback (most recent call last):
  File "/home/dnnf/.venv/bin/flit", line 8, in <module>
    sys.exit(main())
  File "/home/dnnf/.venv/lib/python3.7/site-packages/flit/__init__.py", line 172, in main
    pth=args.pth_file).install()
  File "/home/dnnf/.venv/lib/python3.7/site-packages/flit/install.py", line 413, in install
    self.install_directly()
  File "/home/dnnf/.venv/lib/python3.7/site-packages/flit/install.py", line 298, in install_directly
    self.install_requirements()
  File "/home/dnnf/.venv/lib/python3.7/site-packages/flit/install.py", line 252, in install_requirements
    check_call(cmd)
  File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/dnnf/.venv/bin/python3.7', '-m', 'pip', 'install', '-r', '/tmp/tmp840r181irequirements.txt']' died with <Signals.SIGKILL: 9>.
The command '/bin/bash -c ./install.sh --include-cleverhans --include-foolbox --include-tensorfuzz --python python3.7' returned a non-zero code: 1

**Comment by dlshriver** [comment]
I think this error is being thrown by pip/flit due to issues when trying to download and install pytorch. For some reason installing pytorch in the docker image can be flaky. Trying to run the build again might work. Otherwise, we do provide pre-built docker images on [Docker Hub](https://hub.docker.com/r/dlshriver/dnnf), which you can get with `docker pull dlshriver/dnnf`.
